# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0007_auto_20160206_2118'),
        ('irnas_koruza', '0005_auto_20160206_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='KoruzaLinkMonitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.IntegerField(editable=False, null=True)),
                ('annotations', models.TextField(default='{}', editable=False)),
                ('neighbour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Node')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_irnas_koruza.koruzalinkmonitor_set+', to='contenttypes.ContentType')),
                ('root', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_irnas_koruza_koruzalinkmonitor', to='core.Node')),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'abstract': False,
            },
        ),
    ]
