# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-05 15:08
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0008_auto_20161013_1344'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='locationconfig',
            managers=[
                ('geo_objects', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
