# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 22:43
from __future__ import unicode_literals

import datetime
from django.db import migrations
import timedelta.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cgm', '0015_auto_20160206_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocatednetworkconfig',
            name='lease_duration',
            field=timedelta.fields.TimedeltaField(choices=[(datetime.timedelta(0, 900), '15 minutes'), (datetime.timedelta(0, 1800), '30 minutes'), (datetime.timedelta(0, 3600), '1 hour'), (datetime.timedelta(0, 7200), '2 hours'), (datetime.timedelta(0, 14400), '4 hours'), (datetime.timedelta(0, 43200), '12 hours'), (datetime.timedelta(1), '24 hours')], default=b'15min', verbose_name='Lease Duration'),
        ),
        migrations.AlterField(
            model_name='staticnetworkconfig',
            name='lease_duration',
            field=timedelta.fields.TimedeltaField(choices=[(datetime.timedelta(0, 900), '15 minutes'), (datetime.timedelta(0, 1800), '30 minutes'), (datetime.timedelta(0, 3600), '1 hour'), (datetime.timedelta(0, 7200), '2 hours'), (datetime.timedelta(0, 14400), '4 hours'), (datetime.timedelta(0, 43200), '12 hours'), (datetime.timedelta(1), '24 hours')], default=b'15min', verbose_name='Lease Duration'),
        ),
    ]
