# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-23 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgm', '0018_switch_interfaces'),
    ]

    operations = [
        migrations.AddField(
            model_name='dhcpnetworkconfig',
            name='default_route',
            field=models.BooleanField(default=True, verbose_name='Create default route via received gateway'),
        ),
        migrations.AddField(
            model_name='dhcpnetworkconfig',
            name='dns',
            field=models.BooleanField(default=False, verbose_name='Use received DNS server'),
        ),
    ]
