from django.contrib.syndication.feeds import Feed
from wlanlj.nodes.models import Event

class LatestEvents(Feed):
  title = "wlan ljubljana - Latest mesh events"
  link = "http://nodes.wlan-lj.net"
  description = "Latest events generated by nodes participating in the mesh."

  def items(self):
    return Event.objects.order_by('-timestamp')[:30]

  def item_link(self, item):
    return "http://nodes.wlan-lj.net/nodes/node/%s#evt%s" % (item.node.ip, item.id)

