# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-13 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields
import nodewatcher.core.registry.fields


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0005_auto_20160206_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleconfig',
            name='annotations',
            field=jsonfield.fields.JSONField(default=dict, editable=False),
        ),
        migrations.AlterField(
            model_name='roleconfig',
            name='roles',
            field=nodewatcher.core.registry.fields.RegistryMultipleChoiceField(base_field=models.CharField(choices=[(b'system', 'System node'), (b'border-router', 'Border router'), (b'vpn-server', 'VPN server'), (b'redundancy-required', 'Node with redundant links requirement')], max_length=50), blank=True, default=list, enum_id=b'core.roles#roles', null=True, regpoint=b'node.config', size=None),
        ),
    ]
