# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-08 13:08
from __future__ import unicode_literals

from django.db import migrations

from nodewatcher.core.generator.cgm import device_migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cgm', '0016_auto_20160206_2343'),
    ]

    operations = [
        device_migrations.RenameDevice('gl-inetv1', 'gl-inet6416av1')
    ]
