# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-11 11:57
from __future__ import unicode_literals

from django.db import migrations

from nodewatcher.core.generator.cgm import device_migrations

class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_change_glinet_id'),
    ]

    operations = [
        device_migrations.RenameDevice('tp-cpe210', 'tp-cpe210-v1'),
        device_migrations.RenameDevice('tp-cpe220', 'tp-cpe220-v1'),
        device_migrations.RenameDevice('tp-cpe510', 'tp-cpe510-v1'),
        device_migrations.RenameDevice('tp-cpe520', 'tp-cpe520-v1'),
    ]
