from django.contrib.syndication.feeds import Feed, FeedDoesNotExist
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.models import User
from wlanlj.nodes.models import Event

class LatestEvents(Feed):
  link = "http://nodes.wlan-lj.net"
  description = "Latest events generated by nodes participating in the mesh."

  def get_object(self, bits):
    if len(bits) != 1:
      return None

    return User.objects.get(id = bits[0])
  
  def title(self, obj):
    if not obj:
      return "wlan ljubljana - Latest mesh events"

    return "wlan ljubljana - Mesh events for %s" % obj.username
  
  def items(self, obj):
    if not obj:
      return Event.objects.order_by('-timestamp')[:30]

    return Event.objects.filter(node__owner = obj).order_by('-timestamp')[:30]

  def item_pubdate(self, item):
    return item.timestamp

  def item_link(self, item):
    return "http://nodes.wlan-lj.net/nodes/node/%s#evt%s" % (item.node.ip, item.id)

