# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-21 04:25
from __future__ import unicode_literals

from django.db import migrations
import nodewatcher.core.registry.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20160206_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticiprouteridconfig',
            name='address',
            field=nodewatcher.core.registry.fields.IPAddressField(help_text='A static IP address is not allocated from an IP pool. A conflict with an IP allocated from an IP pool is possible. Consider allocating it from the IP pool and use "hint" to suggest the wanted IP address.'),
        ),
    ]
