# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-13 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20160821_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalconfig',
            name='annotations',
            field=models.TextField(default='{}', editable=False),
        ),
        migrations.AlterField(
            model_name='node',
            name='registry_metadata',
            field=models.TextField(default='{}', editable=False),
        ),
        migrations.AlterField(
            model_name='routeridconfig',
            name='annotations',
            field=models.TextField(default='{}', editable=False),
        ),
    ]
