# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-21 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors_generic', '0007_auto_20161013_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericsensormonitor',
            name='group',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
