from django.conf import settings

DATE_FORMAT = settings.DATE_FORMAT
TIME_FORMAT = settings.TIME_FORMAT
DATETIME_FORMAT = settings.DATETIME_FORMAT
YEAR_MONTH_FORMAT = settings.YEAR_MONTH_FORMAT
MONTH_DAY_FORMAT = settings.MONTH_DAY_FORMAT
SHORT_DATE_FORMAT = settings.SHORT_DATE_FORMAT
SHORT_DATETIME_FORMAT = settings.SHORT_DATETIME_FORMAT
FIRST_DAY_OF_WEEK = settings.FIRST_DAY_OF_WEEK
DECIMAL_SEPARATOR = settings.DECIMAL_SEPARATOR
THOUSAND_SEPARATOR = settings.THOUSAND_SEPARATOR
NUMBER_GROUPING = settings.NUMBER_GROUPING
