# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-23 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [(b'channel_allocation', '0001_initial'), (b'channel_allocation', '0002_remove_nodechannel_channel_width'), (b'channel_allocation', '0003_auto_20160822_0426')]

    initial = True

    dependencies = [
        ('monitor', '0006_auto_20160206_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optimal_start_frequency', models.PositiveIntegerField()),
                ('optimal_channel_width', models.PositiveIntegerField()),
                ('optimal_channel_interference', models.FloatField()),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.WifiInterfaceMonitor')),
            ],
        ),
    ]
