# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-22 02:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel_allocation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodechannel',
            name='channel_width',
        ),
    ]
