INSERT INTO nodes_pool(family, network, cidr, allocated, default_prefix_len) VALUES(4, '10.14.128.0', 17, 0, 27);
INSERT INTO nodes_pool(family, network, cidr, allocated, default_prefix_len) VALUES(4, '10.14.112.0', 20, 0, 27);
INSERT INTO nodes_project(name, description, pool_id, sticker) VALUES('Ljubljana', '', 1, 'ljubljana.tex');
INSERT INTO nodes_project(name, description, pool_id, sticker) VALUES('Nova Gorica', '', 2, 'ljubljana.tex');
INSERT INTO generator_template(name, openwrt_version, arch, iface_wifi, iface_lan, iface_wan, driver, channel, port_layout, imagebuilder, imagefile) VALUES('Linksys WRT54GL (2.4 kernel)', 'new', 'mipsel', 'wl0', 'eth0.0', 'eth0.1', 'broadcom', 8, 'wrt54gl', 'imagebuilder.brcm24', 'openwrt-wrt54g-squashfs.bin');
INSERT INTO generator_template(name, openwrt_version, arch, iface_wifi, iface_lan, iface_wan, driver, channel, port_layout, imagebuilder, imagefile) VALUES('Linksys WRT54GL (2.6 kernel) [EXPERIMENTAL]', 'new', 'mipsel', 'wlan0', 'eth0.0', 'eth0.1', 'mac80211', 8, 'wrt54gl', 'imagebuilder.broadcom', 'openwrt-wrt54g-squashfs.bin');
INSERT INTO generator_template(name, openwrt_version, arch, iface_wifi, iface_lan, iface_wan, driver, channel, port_layout, imagebuilder, imagefile) VALUES('Buffalo WHR-HP-G54 (2.4 kernel)', 'new', 'mipsel', 'wl0', 'eth0.0', 'eth0.1', 'broadcom', 8, 'whr-hp-g54', 'imagebuilder.brcm24', 'openwrt-brcm-2.4-squashfs.trx');
INSERT INTO generator_template(name, openwrt_version, arch, iface_wifi, iface_lan, iface_wan, driver, channel, port_layout, imagebuilder, imagefile) VALUES('Fonera (2.6 kernel)', 'new', 'mips', 'ath0', '', 'eth0','atheros', 8, 'fonera', 'imagebuilder.atheros', 'openwrt-atheros-root.jffs2-64k,openwrt-atheros-vmlinux.lzma');
INSERT INTO generator_template(name, openwrt_version, arch, iface_wifi, iface_lan, iface_wan, driver, channel, port_layout, imagebuilder, imagefile) VALUES('Linksys WRT54GS (2.4 kernel)', 'new', 'mipsel', 'wl0', 'eth0.0', 'eth0.1', 'broadcom', 8, 'wrt54gs', 'imagebuilder.brcm24', 'openwrt-wrt54gs-squashfs.bin');
INSERT INTO generator_template(name, openwrt_version, arch, iface_wifi, iface_lan, iface_wan, driver, channel, port_layout, imagebuilder, imagefile) VALUES('Fonera+ (2.6 kernel)', 'new', 'mips', 'ath0', 'eth0.0', 'eth0.1','atheros', 8, 'fonera+', 'imagebuilder.atheros', 'openwrt-atheros-root.jffs2-64k,openwrt-atheros-vmlinux.lzma');
INSERT INTO generator_ifacetemplate(template_id, type, ifname) VALUES(1, 0, 'eth0.0');
INSERT INTO generator_ifacetemplate(template_id, type, ifname) VALUES(1, 1, 'eth0.1');
INSERT INTO generator_ifacetemplate(template_id, type, ifname) VALUES(1, 2, 'wl0');
INSERT INTO generator_ifacetemplate(template_id, type, ifname) VALUES(2, 0, 'eth0.0');
INSERT INTO generator_ifacetemplate(template_id, type, ifname) VALUES(2, 1, 'eth0.1');
INSERT INTO generator_ifacetemplate(template_id, type, ifname) VALUES(2, 2, 'wl0');
INSERT INTO generator_ifacetemplate(template_id, type, ifname) VALUES(3, 0, 'eth0.0');
INSERT INTO generator_ifacetemplate(template_id, type, ifname) VALUES(3, 1, 'eth0.1');
INSERT INTO generator_ifacetemplate(template_id, type, ifname) VALUES(3, 2, 'wl0');
INSERT INTO generator_ifacetemplate(template_id, type, ifname) VALUES(4, 0, 'eth0');
INSERT INTO generator_ifacetemplate(template_id, type, ifname) VALUES(4, 1, 'eth0');
INSERT INTO generator_ifacetemplate(template_id, type, ifname) VALUES(4, 2, 'ath0');
INSERT INTO generator_ifacetemplate(template_id, type, ifname) VALUES(5, 0, 'eth0.0');
INSERT INTO generator_ifacetemplate(template_id, type, ifname) VALUES(5, 1, 'eth0.1');
INSERT INTO generator_ifacetemplate(template_id, type, ifname) VALUES(5, 2, 'wl0');
INSERT INTO generator_ifacetemplate(template_id, type, ifname) VALUES(6, 0, 'eth0.0');
INSERT INTO generator_ifacetemplate(template_id, type, ifname) VALUES(6, 1, 'eth0.1');
INSERT INTO generator_ifacetemplate(template_id, type, ifname) VALUES(6, 2, 'ath0');

