# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-07 12:41
from __future__ import unicode_literals

from django.db import migrations
import nodewatcher.core.registry.fields


def add_wifi_mesh_type(apps, schema_editor):
    """
    Populates the top_level field for existing IpPool instances.
    """

    NetworkProfileConfig = apps.get_model('defaults_network_profile', 'NetworkProfileConfig')
    for profile in NetworkProfileConfig.objects.all():
        if 'no-wifi-mesh' in profile.profiles:
            profile.wireless_mesh_type = None
        elif 'wifi-mesh-80211s' in profile.profiles:
            profile.wireless_mesh_type = '80211s'
        else:
            profile.wireless_mesh_type = 'ad-hoc'

        profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('defaults_network_profile', '0006_auto_20161013_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkprofileconfig',
            name='wireless_mesh_type',
            field=nodewatcher.core.registry.fields.RegistryChoiceField(b'node.config', b'network.profile#wireless_mesh_type', blank=True, default=b'ad-hoc', help_text='Type of interface that should be used for wireless meshihng.', max_length=50, null=True),
        ),
        migrations.RunPython(add_wifi_mesh_type, reverse_code=migrations.RunPython.noop),
    ]
