# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-07 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irnas_sfp', '0003_json_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='sfpmonitor',
            name='rx_power_dbm',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sfpmonitor',
            name='rx_power_dbm_maximum',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sfpmonitor',
            name='rx_power_dbm_minimum',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sfpmonitor',
            name='rx_power_dbm_variance',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sfpmonitor',
            name='rx_power_maximum',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sfpmonitor',
            name='rx_power_minimum',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sfpmonitor',
            name='rx_power_variance',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sfpmonitor',
            name='temperature_maximum',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sfpmonitor',
            name='temperature_minimum',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sfpmonitor',
            name='temperature_variance',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sfpmonitor',
            name='tx_bias_minimum',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sfpmonitor',
            name='tx_bias_maximum',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sfpmonitor',
            name='tx_bias_variance',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sfpmonitor',
            name='tx_power_maximum',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sfpmonitor',
            name='tx_power_minimum',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sfpmonitor',
            name='tx_power_variance',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sfpmonitor',
            name='vcc_maximum',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sfpmonitor',
            name='vcc_minimum',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sfpmonitor',
            name='vcc_variance',
            field=models.FloatField(null=True),
        ),
    ]
