# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-07 16:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('irnas_sfp', '0004_statistics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sfpmonitor',
            name='rx_power_dbm_variance',
        ),
    ]
