# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-22 19:05
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unknown_nodes', '0003_auto_20160206_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unknownnode',
            name='certificate',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
