#!/bin/bash

DUMP="$1"
if which gsed > /dev/null; then
	SED="gsed"
else
	SED="sed"
fi

$SED -f - -i ${DUMP} <<EOF
s/public\.ip4r/character varying\(32\)/g
s/wlansi_nw\./public./g
s/wlansi_nw/nodewatcher/g
s/wlansi_cms\./public./g
s/wlansi_cms/nodewatcher/g
s/CREATE INDEX nodes_pool_ip_subnet_ip4 ON nodes_pool USING gist (ip_subnet);//g
s/CREATE INDEX nodes_subnet_ip_subnet_ip4 ON nodes_subnet USING gist (ip_subnet);//g
s/SET search_path = nodewatcher, pg_catalog;/SET search_path = public, pg_catalog;/g
s/CREATE SCHEMA nodewatcher;//g
s/ALTER SCHEMA nodewatcher OWNER TO postgres;//g
s/REVOKE ALL ON SCHEMA nodewatcher FROM PUBLIC;//g
s/REVOKE ALL ON SCHEMA nodewatcher FROM postgres;//g
s/GRANT ALL ON SCHEMA nodewatcher TO postgres;//g
s/GRANT ALL ON SCHEMA nodewatcher TO nodewatcher;//g
s/GRANT USAGE ON SCHEMA nodewatcher TO nodewatcher;//g
EOF

