#!/bin/bash -e

# Activate virtualenv Python environment
. /srv/nodewatcher/env_nodewatcher/bin/activate

# Dump database
cd /srv/nodewatcher/nodewatcher/nodewatcher
python manage.py dumptestdata --settings=frontend.settings_production /srv/www/bindist/data/dump.tar.bz2

# Prepare fresh simulator dataset
mkdir /tmp/__simulator
cd /tmp/__simulator
cp -R /srv/nodewatcher/nodewatcher/nodewatcher/monitor/simulator/data/* .
rm -f nodes/.placeholder
tar cjf /srv/www/bindist/data/simulator-dataset.tar.bz2 *
cd
rm -rf /tmp/__simulator
