#!/bin/bash
python manage.py syncdb --noinput
python manage.py migrate djcelery 0001 --fake
python manage.py migrate frontend.nodes 0001 --fake
python manage.py migrate frontend.generator 0001 --fake
python manage.py migrate frontend.policy 0001 --fake
python manage.py migrate cgm --noinput
python manage.py migrate --noinput
