#!/bin/bash -e

PSQL_USER_ARG="-U postgres"
PSQL_HOST="localhost"

CONTRIB_DIR=""
POSTGIS_DIR=""
if [ -d /usr/share/postgresql/8.4 ]; then
    CONTRIB_DIR="/usr/share/postgresql/8.4/contrib"
    POSTGIS_DIR="/usr/share/postgresql/8.4/contrib/postgis-1.5"
fi
if [ -d /usr/share/postgresql/9.1 ]; then
    CONTRIB_DIR="/usr/share/postgresql/9.1/contrib"
    POSTGIS_DIR="/usr/share/postgresql/9.1/contrib/postgis-1.5"
fi
if [ -d /usr/share/postgresql-8.3 ]; then
    CONTRIB_DIR="/usr/share/postgresql-8.3/contrib"
    POSTGIS_DIR="/usr/share/postgresql-8.3/contrib/postgis-1.5"
fi
if [ -d /usr/local/share/postgresql ]; then
    CONTRIB_DIR="/usr/local/share/postgresql/contrib"
    POSTGIS_DIR="/usr/local/share/postgis"
    PSQL_USER_ARG=""
fi
if [ -d /usr/local/Cellar/postgresql9/9.0.11 ]; then
    CONTRIB_IDR="/usr/local/Cellar/postgresql9/9.0.11/share/postgresql9/contrib"
    PSQL_USER_ARG=""
fi
if [ -d /usr/local/Cellar/postgis15/1.5.8 ]; then
    POSTGIS_DIR="/usr/local/Cellar/postgis15/1.5.8/share/postgis"
fi

if  [[ -ne "$CONTRIB_DIR" && -ne "$POSTGIS_DIR" ]]; then
    echo "!!! PostgreSQL or PostGIS contrib directories not found."
    echo "!!! Please edit the database initialization script!"
    exit 1
fi

# Drop can fail if there is no database already defined
dropdb -h ${PSQL_HOST} ${PSQL_USER_ARG} nodewatcher || true
dropuser -h ${PSQL_HOST} ${PSQL_USER_ARG} nodewatcher || true
createuser -h ${PSQL_HOST} ${PSQL_USER_ARG} -S -D -R nodewatcher || true
createdb -h ${PSQL_HOST} ${PSQL_USER_ARG} -E UNICODE -T template0 -O nodewatcher nodewatcher
createlang -h ${PSQL_HOST} ${PSQL_USER_ARG} plpgsql nodewatcher || true
psql -h ${PSQL_HOST} ${PSQL_USER_ARG} -d nodewatcher -f ${POSTGIS_DIR}/postgis.sql
psql -h ${PSQL_HOST} ${PSQL_USER_ARG} -d nodewatcher -f ${POSTGIS_DIR}/spatial_ref_sys.sql
psql -h ${PSQL_HOST} ${PSQL_USER_ARG} -d nodewatcher -c "ALTER TABLE geometry_columns OWNER TO nodewatcher;"
psql -h ${PSQL_HOST} ${PSQL_USER_ARG} -d nodewatcher -c "ALTER VIEW geography_columns OWNER TO nodewatcher;"
psql -h ${PSQL_HOST} ${PSQL_USER_ARG} -d nodewatcher -c "ALTER TABLE spatial_ref_sys OWNER TO nodewatcher;"
