# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-13 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qos_base', '0002_auto_20160206_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfaceqosconfig',
            name='annotations',
            field=models.TextField(default='{}', editable=False),
        ),
    ]
